import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../globals.css";
import Header from "@/components/navigation/header";
import Footer from "@/components/navigation/footer";
import FooterCta from "@/components/sections/footer-cta";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{
    lang: string;
  }>;
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lang } = await params;
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <Header lang={lang as "fr" | "en"} />
        {children}
        <FooterCta />
        <Footer />
      </body>
    </html>
  );
}
